name = "hooktea"
main = "worker.js"
compatibility_date = "2026-04-06"
account_id = "8058cf61f0cd44c4edd78080b193033a"

[vars]
LINEPAY_ENV = "production"
LINEPAY_CHANNEL_ID = "2004409296"
LINEPAY_CURRENCY = "TWD"
REMITTANCE_INFO = """
永豐銀行 Bank SinoPac
銀行代號：807
往來行：竹北自強分行
戶名：江鴻卡寧區國際茶行銷有限公司
帳號：039-018-0005831-8
SWIFT CODE：SINOTWTP
匯款後請保留收據，並回覆匯款帳號末五碼。
"""

[[kv_namespaces]]
binding = "ACTION_DATA"
id = "6838e4176140433281b3a120a9fe964a"

[[r2_buckets]]
binding = "act-image"
bucket_name = "hooktea-image"

[[d1_databases]]
binding = "DB"
database_name = "hooktea"
database_id = "1a144f54-3b58-4587-8c1a-db42c848ef0e"
